import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GetStaticProps } from 'next'
import Link from 'next/link'
import User, {IUser} from "../class/user"

export default function Home() {
  const user: IUser = new User("三浦", "壱生", 11)
  console.log(`user`, user.getUserInfo())
  console.log(`user`, user.updateUser({firstName: "山田", lastName: "太郎"}))

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>
        <Link href={'/isr'}>
          <a>ISR動作確認ページへ</a>
        </Link>
        <Link href={'/ssr'}>
          <a>SSR動作確認ページへ</a>
        </Link>
        <Link href={'/ssg'}>
          <a>SSG動作確認ページへ</a>
        </Link>
      </main>
    </div>
  )
}